version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev-track-habits
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: habit_tracker
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - localnet

volumes:
  mysql_data:

networks:
  localnet:
    driver: bridge
